### ISSUE TITLE
Dockerfile missing command for wget subread file?

### ISSUE THREAD

**Issue by brettvanderwerff** [MaayanLab/Zika-RNAseq-Pipeline#4]
Hi, 

I am working through your analysis pipeline here. If I pull the image from dockerhub, everything seems to work fine, but I was trying to build the image from the Dockerfile and I kept running into an error that said there was no file subread-1.4.6-p2-Linux-x86_64.tar.gz when trying to perform the step:

`RUN tar zxvf subread-1.4.6-p2-Linux-x86_64.tar.gz`

I noticed there is no command to download subread in the dockerfile like the other packages, so

I added the following line before the step that throws the error:

`RUN wget -O subread-1.4.6-p2-Linux-x86_64.tar.gz --no-check-certificate https://sourceforge.net/projects/subread/files/subread-1.4.6-p2/subread-1.4.6-p2-Linux-x86_64.tar.gz`

Everything seems to build fine now. I am kind of new to Docker, could someone verify that this is an issue. Hopefully I have not missed something obvious. If it is an issue, then I can put in a PR. Thanks for putting together this amazing repo.

**Comment by wangz10** [comment]
Hi @brettvanderwerff , 

Thank you for reporting this! This is indeed an issue for re-building the Docker image as I had this file manually downloaded before when building the Docker image.

Please submit a PR. 

Thanks!

**Comment by wangz10** [comment]
Resolved in #5
